version : "2"
services:
  vote:
   image: eesprit/voting-app-vote
   ports:
     - "5000:80"
   links:
     - redis
  redis:
   image: redis:alpine 
  worker:
   image: eesprit/voting-app-worker
   links:
     - redis  
     - db
  db:
   image: postgres:9.4
  result:
   image: eesprit/voting-app-result
   links: 
     - db
   ports:
     - "5000:80"